#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
k=21
b=300
m=300
a=150
f=
threads=`nproc`
infile=
outdir="./bubbz_out"
align="True"
noseq=""

usage () { echo "Usage: [-k <odd integer>] [-b <integer>] [-m <integer>] [-a <integer>] [-t <integer>] [-f <integer>] [-o <output_directory>] <input file> " ;}

options='t:k:b:a:m:o:f:nh'
while getopts $options option
do
    case $option in
	k  ) k=$OPTARG;;
	b  ) b=$OPTARG;;
	m  ) m=$OPTARG;;
	a  ) a=$OPTARG;;
	t  ) threads=$OPTARG;;
	o  ) outdir=$OPTARG;;
	f  ) f=$OPTARG;;
	n  ) align="False";;
	h  ) usage; exit;;
	\? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
	:  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
	*  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
    esac
done

shift $((OPTIND-1))


if [ -z "$1" ]
then
	echo "You must provide the input file name" >&2
	exit 1
fi

min() {
   [ "$1" -lt "$2" ] && echo $1 || echo $2
}

max() {
   [ "$1" -lt "$2" ] && echo $2 || echo $1
}



if [ -z "$f" ]
then
        export memory_avail=`free -g -w | head -2 | tail -1 | awk '{print $2}'`
        total_size=0
        IFS=' ' read -ra ADDR <<< "$infile"
        for i in "${ADDR[@]}"; do
                total_size=$((total_size + `stat -c "%s" $i`))
        done

        total_size=$((total_size * 3 / 1000000000))
        f=$( min $total_size $memory_avail )
        f=$( max $f 4 )
fi

min() {
   [ "$1" -lt "$2" ] && echo $1 || echo $2
}

infile=$1
twopaco_threads=$( min $threads 16 )
dbg_file=$outdir/de_bruijn_graph.dbg

mkdir -p $outdir
echo "Constructing the graph..."
$DIR/twopaco --tmpdir $outdir -t $twopaco_threads -k $k --filtermemory $f -a $a -o $dbg_file $infile
$DIR/bubbz-map --graph $dbg_file $infile -k $k -b $b -o $outdir -m $m -t $threads

rm $dbg_file

